setenv('DATA_DIR','/data/MK6240_datasets_for_Tao/SMK005/PET')
setenv('MRI_DIR','/data/MK6240_datasets_for_Tao/SMK005/MRI')
setenv('SPM_DIR','/code/matlab/spm12')
setenv('FREESURFER_HOME','/usr/local/freesurfer')
setenv('MAGIA_PATH','/code/matlab/magia')
setenv('MAGIA_ARCHIVE','/code/work/template')
setenv('FS_FINAL_DIR','/data/MK6240_datasets_for_Tao/SMK005/fsfinal')
setenv('FS_TEMP_DIR','/data/MK6240_datasets_for_Tao/SMK005/fstemp')

% setenv('SPM_DIR','/data/')
% setenv('FS_FINAL_DIR','/data/')
% setenv('FS_TEMP_DIR','/data/')